# Generated by Django 2.0.3 on 2020-05-18 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionprice',
            name='optionValue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='optionPrice', to='orders.OptionValue'),
        ),
    ]
