# Generated by Django 2.0.3 on 2020-05-19 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200518_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='options',
        ),
        migrations.AddField(
            model_name='product',
            name='option1',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.PROTECT, to='orders.Option'),
        ),
    ]
