# Generated by Django 2.0.3 on 2020-05-20 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200519_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price0', models.FloatField()),
                ('price1', models.FloatField()),
                ('price2', models.FloatField()),
                ('price3', models.FloatField()),
                ('priceSpecial', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PizzaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Pizza')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SubExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SubItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extras', models.ManyToManyField(blank=True, to='orders.SubExtra')),
            ],
        ),
        migrations.RemoveField(
            model_name='optionprice',
            name='optionValue',
        ),
        migrations.RemoveField(
            model_name='optionprice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='optionvalue',
            name='option',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='optionsValue',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='option1',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='OptionPrice',
        ),
        migrations.DeleteModel(
            name='OptionValue',
        ),
        migrations.AddField(
            model_name='subitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Product'),
        ),
        migrations.AddField(
            model_name='simpleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Product'),
        ),
        migrations.AddField(
            model_name='pizzaitem',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='orders.PizzaTopping'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pizzaItem',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='orders.PizzaItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='simpleItem',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='orders.SimpleItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='subItem',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='orders.SubItem'),
            preserve_default=False,
        ),
    ]
