# Generated by Django 2.0.3 on 2020-05-20 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
