# Generated by Django 2.0.3 on 2020-05-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200521_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
