# Generated by Django 2.0.3 on 2020-06-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200525_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzaitem',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='pizzaitem',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='simpleitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='subitem',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='subitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='pizzaItem',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='simpleItem',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='subItem',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='options',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PizzaItem',
        ),
        migrations.DeleteModel(
            name='SimpleItem',
        ),
        migrations.DeleteModel(
            name='SubItem',
        ),
    ]
